###
post http://localhost:9000/api/busstops/create
Content-Type: application/json

{
    "busStopName":"Дулааны цахилгаан станц 3 (зүүн)",
    "busStopCoord":[47.8992785639388, 106.8679574858624]
}

###
get https://simpletransit.onrender.com/api/busstops


