###
post http://localhost:9000/api/busstops/create
Content-Type: application/json

{
    "busStopName":"Зүүн 4 зам(урд)",
    "busStopCoord":[47.91881723083494, 106.94091247528337]
}

###
get http://localhost:9000/api/busstops