###
post http://localhost:9000/api/user/getallnotfriends
Content-Type: application/json

{
    "userId":"64657d792ac7e347e03945c4",
    "name": "t"
}

###
post http://localhost:9000/api/user/getallfriends
Content-Type: application/json

{
    "userId":"64657d792ac7e347e03945c4"
}

###
post http://localhost:9000/api/user/signup
Content-Type: application/json

{
    "name":"Bitaamin",
    "email":"htamir80@gmail.com",
    "password":"Tamirpro133"
}