###
post http://localhost:9000/api/user/getallnotfriends
Content-Type: application/json

{
    "userId":"6467242e79601e61e1a34a93",
    "name": "t"
}

###
post http://localhost:9000/api/user/getallfriends
Content-Type: application/json

{
    "userId":"6467242e79601e61e1a34a93"
}

###
post http://localhost:9000/api/user/signup
Content-Type: application/json

{
    "name":"test7",
    "email":"t7@gmail.com",
    "password":"12345678"
}

###
post http://localhost:9000/api/user/login
Content-Type: application/json

{
  
    "email":"test10.gmail.com",
    "password":"12345678",
    "location":[47.92496571176237,106.9284247416154]
    }

### 
post http://localhost:9000/api/user/getone
Content-Type: application/json

{
    "userId":"6467242e79601e61e1a34a93"
}