###
post http://localhost:9000/api/user/connection
Content-Type: application/json

{
    "requester":"64657d592ac7e347e03945c2",
    "recipient":"64657d792ac7e347e03945c4",
    "status":"accepted"}

###
post http://localhost:9000/api/user/connection
Content-Type: application/json

{
    
}